### PR TITLE
Fixed regexp variable matching rule

### PR DESCRIPTION
**Pull request by sup-ham**
#116 #44

Additional notes for this regexp rule.
-    {dot..dot} characters considered is not variable
-    {variable.} can't contains dot character at the end

### CODE REVIEW

**Comment by sup-ham** [comment]
I don't know how to test. I try adding to be error test and results no errors at all.

**Comment by frigus02** [comment]
Thanks. This regular expression looks good. This is unfortunately a breaking change. I wonder how to best announce this change.

- It might be best to describe the naming restrictions here: https://github.com/frigus02/RESTer/blob/cfaca20baa118391086933a2b82e3339bdc29d39/src/site/elements/controls/rester-variables-input.js#L31-L35
- And ideally we would apply the same regex as a `pattern` to the environment variable input field here:

  https://github.com/frigus02/RESTer/blob/cfaca20baa118391086933a2b82e3339bdc29d39/src/site/elements/controls/rester-edit-environment-dialog.js#L77-L81

  I hope that `pattern="[\w$-]+(\.[\w$-]+)*"` works.

Regarding tests, what happens when you run `yarn test` locally. It _should_ run jest and print something similar to here in Travis: https://travis-ci.com/github/frigus02/RESTer/builds/159996893#L362.

**Comment by sup-ham** [comment]
my test was done, yesterday I facing watchman. problem.

For naming restriction I consider use help page. For announcing the changes. 
just like the present notice 
image 
or may be 
image


The pattern attribute, looks nice too.

**Comment by frigus02** [comment]
Sorry for the late reply. This somehow slipped through the cracks. Good to hear that tests are working for you now.

I'm not a fan of help pages or user documentation on this repo, because users would have to find and read that. I find it much easier when the information is where I need it. I could look like this:

image

Regarding the pattern: The environment variable dialog doesn't use pattern, yet. That's because variable names basically had no restriction. Now that they have a pattern would make sense to me. Together with an error message like "Can only contain alphanumeric characters as well as ._-", it should quite clear for users. I hope 🙂

**Comment by sup-ham** [comment]
thats right, missed that, as usually not used `pattern` attribute on input.

**Comment by sup-ham** [comment]
Dialog size need to be adjusted 1000px, what do you think?
image

**Comment by frigus02** [comment]
The pattern for the env name input looks good 👍 

I would still like to show a note on the "Variables" tab on the request page.

Making the env dialog wider sounds like a good idea. We need to do something to make it work on smaller screens, though. Maybe add `max-width: 90vw;` in addition.

**Comment by sup-ham** [comment]
done

**Pull request merged**
