### PR TITLE
Add support for OAuth2 client credentials flow

### PR DESCRIPTION
**Pull request by AdamZ**
Tested in Firefox against an API I'm working on for my employer, and it seems to be working fine.

Let me know if I missed any spots in the code that require changes, or anything else.

### CODE REVIEW

**Comment by frigus02** [comment]
Hey, thanks a lot. This looks really good. Do you want to add yourself to a (new) contributors section on the about page?

I will merge this pull request later this week and push out a new version of RESTer as soon as the current version 2.4.0 has been reviewed.

**Comment by AdamZ** [comment]
Sure, will do. Would that be in README.md? Or were you referring to a different page?

**Comment by frigus02** [comment]
I was thinking about the about page `rester-page-about.html`, but readme or separate authors/contributors file might also make sense. Is there a best practice for this? I'd say put it in the readme for now. I will include this in the about page when I merge it.

**Comment by AdamZ** [comment]
Ah ok, got it. I hadn't noticed the about page in the extension before.

I don't think there's a standard for listing contributors in README vs a separate file, I've seen it done both ways. The only consistent standard is that when there are a lot of people who contribute, then listing them in a separate file is obviously easier.

**Comment by frigus02** [comment]
Thanks. Looks great.

**Pull request merged**
