### PR TITLE
Fixed Custom title for basic auth token

### LINKED ISSUE #135: Add custom title to basic auth token
Currently RESTer uses the `username` as the title for a basic auth token, see screenshot. This complicates things if you have a bunch of credentials for the same username, which is the case if you work with multiple environments (e.g. DEV, TEST and PROD). Then all basic auth tokens have the same name, making it impossible to know which one to use for which environment.

It would be valuable to provide the user the option to set a custom title when creating a new basic auth token, so that tokens for the same username can be distinguished.

Bildschirmfoto 2020-05-25 um 18 00 19

### PR DESCRIPTION
**Pull request by HenningWaack**
Fixes #135 

User can set custom title for basic auth, the default stays the same, i.e. title is set to username if not edited manually.

### CODE REVIEW

**Comment by HenningWaack** [comment]
Hm, not sure why travis fails, `yarn test` works locally on my machine. Can you take a look at this and help me with this issue? Thanks!

**Comment by frigus02** [comment]
Hi. Thanks for working on this. I fixed the CI failure in master. Once you update the branch, the tests should work.

To the changes:

- I'm not sure if we need the `titleManuallyEdited` bit. If I understand it correctly this is used to synchronize the username field with the title field. This is a nice idea. Could we trigger this logic by checking if the title field is empty instead? That seems slightly more robust to me and even work if I enter a title and delete it again.

- Can you run `yarn format` after you're done? It runs prettier and makes whitespace consistent with the rest of the project.

**Comment by HenningWaack** [comment]
Thanks Jan for your help. I merged your master and ran `yarn format`, looks better now :)

Concerning your first point: the variable`titleManuallyEdited` is part of the data because title is set to the username in the dialog as the user is typing. I think leaving the title blank would confuse users and prompt them to type the title manually all the time. Having `titleManuallyEdited` I can track that the title has not been edited and update it on the fly with the username as the user is typing.

Hope that helps, greetings!

**Comment by frigus02** [comment]
Yeah, I realized later that my suggestion wouldn't work. Let's go with what you implemented. 🙂

**Comment by frigus02** [comment]
GitHub seems to be a bit confused about the diff. No idea what happened there. Doesn't matter.

Could you just remove the console.log. I think then this is ready to merge and I will make a release right after.

**Comment by HenningWaack** [comment]
Ok, log msg removed, sorry about that!

**Pull request merged**
